// Random video game data that is added to Firestore
// After you've signed into Friendly Games, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  gameNames: [
    "Eternal Odyssey",
    "Neon Rebellion",
    "Shadow Protocol",
    "Starfall Chronicles",
    "Mystic Realms",
    "Cyber Siege",
    "Dragon's Legacy",
    "Quantum Drift",
    "Valor Rising",
    "Pixel Pioneers",
    "Void Walker",
    "Arcane Legends",
    "Thunder Strike",
    "Galactic Conquest",
    "Phantom Blade",
    "Crystal Quest",
    "Inferno Storm",
    "Rogue Galaxy",
    "Titan's Wrath",
    "Skybound Heroes",
    "Dark Frontier",
    "Elemental Clash",
    "Zombie Outbreak",
    "Speed Demons",
    "Kingdom Siege",
    "Astral Warriors",
    "Dungeon Depths",
    "Mech Assault",
    "Ninja Legends",
    "Ocean Explorer",
    "Battle Royale X",
    "Time Shifters",
    "Wild West Showdown",
    "Space Colony",
    "Monster Hunter Z",
    "Racing Revolution",
    "Puzzle Master",
    "Soccer Champions",
    "Flight Simulator Pro",
    "Farm Life Deluxe",
    "Survival Island",
  ],
  gamePlatforms: [
    "PC",
    "PlayStation",
    "Xbox",
    "Nintendo Switch",
    "Mobile",
    "Steam Deck",
    "Mac",
    "Linux",
    "VR",
    "Cloud Gaming",
    "Cross-Platform",
  ],
  gameGenres: [
    "Action",
    "RPG",
    "FPS",
    "Adventure",
    "Strategy",
    "Simulation",
    "Sports",
    "Racing",
    "Puzzle",
    "Horror",
    "Indie",
    "MMO",
    "Fighting",
  ],
  gameReviews: [
    { text: "Absolutely incredible game, couldn't put it down!", rating: 5 },
    { text: "Best gameplay mechanics I've experienced in years.", rating: 5 },
    { text: "The graphics are stunning and the story is amazing.", rating: 5 },
    { text: "Addictive gameplay with tons of replayability.", rating: 5 },
    { text: "A masterpiece of game design!", rating: 5 },
    { text: "Hours of fun with friends, highly recommend!", rating: 5 },
    { text: "Perfectly balanced difficulty and rewarding progression.", rating: 5 },
    { text: "Incredible soundtrack and immersive world-building.", rating: 5 },
    { text: "Great game with solid mechanics and good replay value.", rating: 4 },
    { text: "Enjoyed it a lot, minor bugs but nothing game-breaking.", rating: 4 },
    { text: "Fun multiplayer experience, worth the price.", rating: 4 },
    { text: "Solid game, but the story could be more engaging.", rating: 3 },
    { text: "Decent gameplay, but gets repetitive after a while.", rating: 3 },
    { text: "Average experience, nothing too special.", rating: 3 },
    { text: "Too many microtransactions, ruined the experience.", rating: 2 },
    { text: "Buggy launch, needs more polish.", rating: 2 },
    { text: "Underwhelming compared to the hype.", rating: 2 },
    { text: "Graphics are nice but gameplay is boring.", rating: 2 },
    { text: "Complete waste of money, unplayable mess.", rating: 1 },
    { text: "Worst game I've played this year, avoid at all costs.", rating: 1 },
    { text: "Crashes constantly, developers don't care.", rating: 1 },
    { text: "Pay-to-win garbage, don't bother.", rating: 1 },
    { text: "Game of the year material, truly exceptional!", rating: 5 },
    { text: "So much content for the price, amazing value.", rating: 5 },
    { text: "The combat system is incredibly satisfying.", rating: 5 },
    { text: "Lost track of time playing this, so good!", rating: 5 },
    { text: "Perfect blend of action and storytelling.", rating: 5 },
    { text: "Innovative gameplay that sets new standards.", rating: 5 },
    { text: "Fantastic co-op experience with friends.", rating: 5 },
    { text: "The open world is breathtaking and full of secrets.", rating: 5 },
    { text: "Great atmosphere and engaging characters.", rating: 4 },
    { text: "Good game, but the grind can be tedious.", rating: 4 },
    { text: "Enjoyable experience with a few flaws.", rating: 4 },
    { text: "Well-made game with smooth performance.", rating: 4 },
    { text: "Fun for casual gaming sessions.", rating: 4 },
    { text: "It's okay, nothing groundbreaking.", rating: 3 },
    { text: "Could use more content updates.", rating: 3 },
    { text: "Mixed feelings, some parts great, others not.", rating: 3 },
    { text: "Expected better from this studio.", rating: 2 },
    { text: "Mediocre at best, forgettable experience.", rating: 2 },
    { text: "Regret buying this, felt unfinished.", rating: 2 },
    { text: "Not worth the full price, wait for a sale.", rating: 2 },
  ],
};
